//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("created-at", Namespace = "", IsNullable = true)]
public partial class createdat
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("via-id", Namespace = "", IsNullable = true)]
public partial class viaid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("is-public", Namespace = "", IsNullable = true)]
public partial class ispublic
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ZenTickts
{

    private ZenTicket[] ticketField;

    private string report_dateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ticket", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ZenTicket[] ticket
    {
        get
        {
            return this.ticketField;
        }
        set
        {
            this.ticketField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string report_date
    {
        get
        {
            return this.report_dateField;
        }
        set
        {
            this.report_dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ZenTicket
{

    private string currenttagsField;

    private string descriptionField;

    private string subjectField;

    private string permissionsField;

    private ticketsTicketAssignedat[] assignedatField;

    private ticketsTicketAssigneeid[] assigneeidField;

    private ticketsTicketBasescore[] basescoreField;

    private createdat[] createdatField;

    private ticketsTicketCurrentcollaborators[] currentcollaboratorsField;

    private ticketsTicketDuedate[] duedateField;

    private ticketsTicketEntryid[] entryidField;

    private ticketsTicketExternalid[] externalidField;

    private ticketsTicketGroupid[] groupidField;

    private ticketsTicketInitiallyassignedat[] initiallyassignedatField;

    private ticketsTicketLatestrecipients[] latestrecipientsField;

    private ticketsTicketNiceid[] niceidField;

    private ticketsTicketOrganizationid[] organizationidField;

    private ticketsTicketOriginalrecipientaddress[] originalrecipientaddressField;

    private ticketsTicketPriorityid[] priorityidField;

    private ticketsTicketRecipient[] recipientField;

    private ticketsTicketRequesterid[] requesteridField;

    private ticketsTicketResolutiontime[] resolutiontimeField;

    private ticketsTicketSolvedat[] solvedatField;

    private ticketsTicketStatusid[] statusidField;

    private ticketsTicketStatusupdatedat[] statusupdatedatField;

    private ticketsTicketSubmitterid[] submitteridField;

    private ticketsTicketTickettypeid[] tickettypeidField;

    private ticketsTicketUpdatedat[] updatedatField;

    private ticketsTicketUpdatedbytypeid[] updatedbytypeidField;

    private viaid[] viaidField;

    private ticketsTicketScore[] scoreField;

    private ticketsTicketProblemid[] problemidField;

    private ticketsTicketHasincidents[] hasincidentsField;

    private ticketsTicketComments[] commentsField;

    private ticketsTicketTicketfieldentries[] ticketfieldentriesField;

    private ticketsTicketLinkings[] linkingsField;

    private ticketsTicketChannel[] channelField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("current-tags", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string currenttags
    {
        get
        {
            return this.currenttagsField;
        }
        set
        {
            this.currenttagsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string subject
    {
        get
        {
            return this.subjectField;
        }
        set
        {
            this.subjectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string permissions
    {
        get
        {
            return this.permissionsField;
        }
        set
        {
            this.permissionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assigned-at", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketAssignedat[] assignedat
    {
        get
        {
            return this.assignedatField;
        }
        set
        {
            this.assignedatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assignee-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketAssigneeid[] assigneeid
    {
        get
        {
            return this.assigneeidField;
        }
        set
        {
            this.assigneeidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("base-score", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketBasescore[] basescore
    {
        get
        {
            return this.basescoreField;
        }
        set
        {
            this.basescoreField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("created-at", IsNullable = true)]
    public createdat[] createdat
    {
        get
        {
            return this.createdatField;
        }
        set
        {
            this.createdatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("current-collaborators", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketCurrentcollaborators[] currentcollaborators
    {
        get
        {
            return this.currentcollaboratorsField;
        }
        set
        {
            this.currentcollaboratorsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("due-date", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketDuedate[] duedate
    {
        get
        {
            return this.duedateField;
        }
        set
        {
            this.duedateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entry-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketEntryid[] entryid
    {
        get
        {
            return this.entryidField;
        }
        set
        {
            this.entryidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("external-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketExternalid[] externalid
    {
        get
        {
            return this.externalidField;
        }
        set
        {
            this.externalidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketGroupid[] groupid
    {
        get
        {
            return this.groupidField;
        }
        set
        {
            this.groupidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("initially-assigned-at", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketInitiallyassignedat[] initiallyassignedat
    {
        get
        {
            return this.initiallyassignedatField;
        }
        set
        {
            this.initiallyassignedatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("latest-recipients", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketLatestrecipients[] latestrecipients
    {
        get
        {
            return this.latestrecipientsField;
        }
        set
        {
            this.latestrecipientsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nice-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketNiceid[] niceid
    {
        get
        {
            return this.niceidField;
        }
        set
        {
            this.niceidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organization-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketOrganizationid[] organizationid
    {
        get
        {
            return this.organizationidField;
        }
        set
        {
            this.organizationidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("original-recipient-address", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketOriginalrecipientaddress[] originalrecipientaddress
    {
        get
        {
            return this.originalrecipientaddressField;
        }
        set
        {
            this.originalrecipientaddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("priority-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketPriorityid[] priorityid
    {
        get
        {
            return this.priorityidField;
        }
        set
        {
            this.priorityidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("recipient", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketRecipient[] recipient
    {
        get
        {
            return this.recipientField;
        }
        set
        {
            this.recipientField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("requester-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketRequesterid[] requesterid
    {
        get
        {
            return this.requesteridField;
        }
        set
        {
            this.requesteridField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("resolution-time", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketResolutiontime[] resolutiontime
    {
        get
        {
            return this.resolutiontimeField;
        }
        set
        {
            this.resolutiontimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("solved-at", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketSolvedat[] solvedat
    {
        get
        {
            return this.solvedatField;
        }
        set
        {
            this.solvedatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketStatusid[] statusid
    {
        get
        {
            return this.statusidField;
        }
        set
        {
            this.statusidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status-updated-at", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketStatusupdatedat[] statusupdatedat
    {
        get
        {
            return this.statusupdatedatField;
        }
        set
        {
            this.statusupdatedatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("submitter-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketSubmitterid[] submitterid
    {
        get
        {
            return this.submitteridField;
        }
        set
        {
            this.submitteridField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ticket-type-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketTickettypeid[] tickettypeid
    {
        get
        {
            return this.tickettypeidField;
        }
        set
        {
            this.tickettypeidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("updated-at", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketUpdatedat[] updatedat
    {
        get
        {
            return this.updatedatField;
        }
        set
        {
            this.updatedatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("updated-by-type-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketUpdatedbytypeid[] updatedbytypeid
    {
        get
        {
            return this.updatedbytypeidField;
        }
        set
        {
            this.updatedbytypeidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("via-id", IsNullable = true)]
    public viaid[] viaid
    {
        get
        {
            return this.viaidField;
        }
        set
        {
            this.viaidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("score", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketScore[] score
    {
        get
        {
            return this.scoreField;
        }
        set
        {
            this.scoreField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problem-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketProblemid[] problemid
    {
        get
        {
            return this.problemidField;
        }
        set
        {
            this.problemidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("has-incidents", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketHasincidents[] hasincidents
    {
        get
        {
            return this.hasincidentsField;
        }
        set
        {
            this.hasincidentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("comments", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketComments[] comments
    {
        get
        {
            return this.commentsField;
        }
        set
        {
            this.commentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ticket-field-entries", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketTicketfieldentries[] ticketfieldentries
    {
        get
        {
            return this.ticketfieldentriesField;
        }
        set
        {
            this.ticketfieldentriesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("linkings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketLinkings[] linkings
    {
        get
        {
            return this.linkingsField;
        }
        set
        {
            this.linkingsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("channel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketChannel[] channel
    {
        get
        {
            return this.channelField;
        }
        set
        {
            this.channelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketAssignedat
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketAssigneeid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketBasescore
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCurrentcollaborators
{

    private string nilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketDuedate
{

    private string typeField;

    private string nilField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketEntryid
{

    private string typeField;

    private string nilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketExternalid
{

    private string nilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketGroupid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketInitiallyassignedat
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketLatestrecipients
{

    private string nilField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketNiceid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketOrganizationid
{

    private string typeField;

    private string nilField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketOriginalrecipientaddress
{

    private string nilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketPriorityid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketRecipient
{

    private string nilField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketRequesterid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketResolutiontime
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketSolvedat
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketStatusid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketStatusupdatedat
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketSubmitterid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketTickettypeid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketUpdatedat
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketUpdatedbytypeid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketScore
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketProblemid
{

    private string nilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketHasincidents
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketComments
{

    private ticketsTicketCommentsComment[] commentField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("comment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketCommentsComment[] comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCommentsComment
{

    private string typeField;

    private string valueField;

    private ticketsTicketCommentsCommentAuthorid[] authoridField;

    private createdat[] createdatField;

    private ispublic[] ispublicField;

    private viaid[] viaidField;

    private ticketsTicketCommentsCommentAttachments[] attachmentsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("author-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketCommentsCommentAuthorid[] authorid
    {
        get
        {
            return this.authoridField;
        }
        set
        {
            this.authoridField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("created-at", IsNullable = true)]
    public createdat[] createdat
    {
        get
        {
            return this.createdatField;
        }
        set
        {
            this.createdatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("is-public", IsNullable = true)]
    public ispublic[] ispublic
    {
        get
        {
            return this.ispublicField;
        }
        set
        {
            this.ispublicField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("via-id", IsNullable = true)]
    public viaid[] viaid
    {
        get
        {
            return this.viaidField;
        }
        set
        {
            this.viaidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attachments", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketCommentsCommentAttachments[] attachments
    {
        get
        {
            return this.attachmentsField;
        }
        set
        {
            this.attachmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCommentsCommentAuthorid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCommentsCommentAttachments
{

    private ticketsTicketCommentsCommentAttachmentsAttachment[] attachmentField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attachment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketCommentsCommentAttachmentsAttachment[] attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCommentsCommentAttachmentsAttachment
{

    private string contenttypeField;

    private string filenameField;

    private string tokenField;

    private string urlField;

    private createdat[] createdatField;

    private ticketsTicketCommentsCommentAttachmentsAttachmentID[] idField;

    private ispublic[] ispublicField;

    private ticketsTicketCommentsCommentAttachmentsAttachmentSize[] sizeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("content-type", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contenttype
    {
        get
        {
            return this.contenttypeField;
        }
        set
        {
            this.contenttypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string filename
    {
        get
        {
            return this.filenameField;
        }
        set
        {
            this.filenameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string token
    {
        get
        {
            return this.tokenField;
        }
        set
        {
            this.tokenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("created-at", IsNullable = true)]
    public createdat[] createdat
    {
        get
        {
            return this.createdatField;
        }
        set
        {
            this.createdatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketCommentsCommentAttachmentsAttachmentID[] id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("is-public", IsNullable = true)]
    public ispublic[] ispublic
    {
        get
        {
            return this.ispublicField;
        }
        set
        {
            this.ispublicField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("size", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketCommentsCommentAttachmentsAttachmentSize[] size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCommentsCommentAttachmentsAttachmentID
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketCommentsCommentAttachmentsAttachmentSize
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketTicketfieldentries
{

    private ticketsTicketTicketfieldentriesTicketfieldentry[] ticketfieldentryField;

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ticket-field-entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ticketsTicketTicketfieldentriesTicketfieldentry[] ticketfieldentry
    {
        get
        {
            return this.ticketfieldentryField;
        }
        set
        {
            this.ticketfieldentryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketTicketfieldentriesTicketfieldentry
{

    private string valueField;

    private ticketsTicketTicketfieldentriesTicketfieldentryTicketfieldid[] ticketfieldidField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ticket-field-id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ticketsTicketTicketfieldentriesTicketfieldentryTicketfieldid[] ticketfieldid
    {
        get
        {
            return this.ticketfieldidField;
        }
        set
        {
            this.ticketfieldidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketTicketfieldentriesTicketfieldentryTicketfieldid
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketLinkings
{

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ticketsTicketChannel
{

    private string nilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nil
    {
        get
        {
            return this.nilField;
        }
        set
        {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("created-at", typeof(createdat), IsNullable = true)]
    [System.Xml.Serialization.XmlElementAttribute("is-public", typeof(ispublic), IsNullable = true)]
    [System.Xml.Serialization.XmlElementAttribute("tickets", typeof(ZenTickts))]
    [System.Xml.Serialization.XmlElementAttribute("via-id", typeof(viaid), IsNullable = true)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
